{% set name = "elapid" %}
{% set version = "0.3.20" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 00062d02c37ad5af357b6b266380688f1d3a1fafa1bb5fdee64a849037889be5

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - descartes >=1.1.0,<2
    - geopandas >=0.7.0,<2
    - numpy >=1.18
    - pandas >=1.0.3,<2
    - pyproj >=3.0,<4
    - rasterio >=1.2.1,<2
    - rtree >=0.9,<2
    - scikit-learn >=0.22.2,<2
    - shapely >=1.7.0,<2
    - tqdm >=4.60.0,<5

test:
  imports:
    - elapid
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://elapid.org
  dev_url: https://github.com/earth-chris/elapid
  summary: Species distribution modeling support tools
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - earth-chris
