{% set name = "elapid" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d15334f58ac8f86ab15e6d74b0b0b7d8e335b0494151ac9c4554fd91ad0d25f4

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry
  run:
    - python >={{ python_min }}
    - descartes >=1.1.0,<2
    - geopandas >=1.0
    - numpy >=2.0
    - pandas >=1.0.3,<3
    - matplotlib >=3.7
    - pyproj >=3.0
    - rasterio >=1.2.1
    - rtree >=0.9
    - scikit-learn >=0.22.2,<2
    - scipy >=1.13
    - shapely >=1.7.0,<2
    - tqdm >=4.60.0,<5

test:
  imports:
    - elapid
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://elapid.org
  dev_url: https://github.com/earth-chris/elapid
  summary: Species distribution modeling support tools
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - earth-chris
