{% set name = "elapid" %}
{% set version = "1.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c66b138c88d9a60362e020b6a35e490a122f533ca7f39624025bda5976f484a4

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - descartes >=1.1.0,<2
    - geopandas >=0.7.0,<2
    - numpy >=1.18,<2
    - pandas >=1.0.3,<2
    - pyproj >=3.0,<4
    - rasterio >=1.2.1,<2
    - rtree >=0.9,<2
    - scikit-learn >=0.22.2,<2
    - shapely >=1.7.0,<2
    - tqdm >=4.60.0,<5

test:
  imports:
    - elapid
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://elapid.org
  dev_url: https://github.com/earth-chris/elapid
  summary: Species distribution modeling support tools
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - earth-chris
